name: Build GoldSnap
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mv sdks-master/* ~/theos/sdks/
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Install ldid
        run: brew install ldid

      - name: Build Dylib
        run: |
          export THEOS=~/theos
          # بناء النسخة النهائية بدون أخطاء التنظيف
          make FINALPACKAGE=1
          # سحب الملف للمجلد الرئيسي بدون عمل strip لتجنب الخطأ
          find .theos/obj -name "*.dylib" -exec cp {} ./GoldSnapV10.dylib \;
          # ختم الملف فقط ليصبح شرعياً
          ldid -S GoldSnapV10.dylib

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GoldSnap-Final
          path: GoldSnapV10.dylib
